title: "Zinan Lin"
email: znecho9@gmail.com
timezone: UTC
baseurl: ""
url: "https://znecho9.github.io"
repository: "znecho9/znecho9.github.io"
permalink: "/:title/"
logo: "assets/images/logo.PNG"
author: Zinan
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

sass:
  sass_dir: _sass
  style: compressed

include:
  - _pages

exclude:
  - Gemfile
  - README.md
  - LICENSE.txt
  - vendor
  - node_modules
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/

authors:
  Zinan:
    name: Zinan Lin
    display_name: Zinan
    avatar: "assets/images/bio-photo.jpg"
    email: znecho9@gmail.com
    web: https://znecho9.github.io
    github: https://github.com/znecho9
    description: "Independent Engineer & Researcher."

social:
  github: https://github.com/znecho9
  email: mailto:znecho9@gmail.com
  website: https://znecho9.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Zinan
  - scope:
      path: ""
      type: publications
    values:
      layout: page
  - scope:
      path: ""
      type: talks
    values:
      layout: page
  - scope:
      path: ""
      type: teaching
    values:
      layout: page
  - scope:
      path: ""
      type: portfolio
    values:
      layout: page
